@startuml

set separator none
hide stereotype

<style>
  root {
    BackgroundColor: #ffffff;
    FontColor: #444444;
  }
  // Element,Person
  .Element-RWxlbWVudCxQZXJzb24= {
    BackgroundColor: #08427b;
    LineColor: #052e56;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #ffffff;
    FontSize: 30;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 200;
  }
  // Element,Software System
  .Element-RWxlbWVudCxTb2Z0d2FyZSBTeXN0ZW0= {
    BackgroundColor: #1168bd;
    LineColor: #0b4884;
    LineStyle: 0;
    LineThickness: 2;
    RoundCorner: 20;
    FontColor: #ffffff;
    FontSize: 30;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 200;
  }
  // Relationship
  .Relationship-UmVsYXRpb25zaGlw {
    LineThickness: 2;
    LineStyle: 10-10;
    LineColor: #444444;
    FontColor: #444444;
    FontSize: 30;
  }
  // transparent element for relationships in legend
  .Element-Transparent {
    BackgroundColor: transparent;
    LineColor: transparent;
    FontColor: transparent;
  }
</style>

person "==Person" <<Element-RWxlbWVudCxQZXJzb24=>>

rectangle "==Software System" <<Element-RWxlbWVudCxTb2Z0d2FyZSBTeXN0ZW0=>>

rectangle "." <<.Element-Transparent>> as 1
1 --> 1 <<Relationship-UmVsYXRpb25zaGlw>> : "Relationship"

@enduml