#!/bin/bash
# ======================================================================
# Guia Rápido - Gerador de Dados Sintéticos
# ======================================================================

echo "======================================================================"
echo "GERADOR DE DADOS SINTÉTICOS - DyraSQL"
echo "======================================================================"
echo ""
echo "Localização: src/scripts/generate_data.py"
echo ""
echo "======================================================================"
echo "EXEMPLOS DE USO:"
echo "======================================================================"
echo ""

echo "1. DATASET PADRÃO (180k registros, 90 dias)"
echo "   cd src/scripts"
echo "   ./generate_data.py"
echo ""

echo "2. DATASET PEQUENO (para testes rápidos)"
echo "   ./generate_data.py --records 10000 --days 7 --output teste-pequeno.sql"
echo ""

echo "3. DATASET MÉDIO (500k registros, 3 meses)"
echo "   ./generate_data.py --records 500000 --days 90 --output teste-medio.sql"
echo ""

echo "4. DATASET GRANDE (baseado em GB)"
echo "   ./generate_data.py --size-gb 5 --output teste-5gb.sql"
echo "   ./generate_data.py --size-gb 10 --output teste-10gb.sql"
echo ""

echo "5. DATASET CUSTOMIZADO (1 ano de dados)"
echo "   ./generate_data.py --records 1000000 --days 365 --start-date 2023-01-01"
echo ""

echo "6. DATASET COM BATCHES MAIORES (para performance)"
echo "   ./generate_data.py --records 5000000 --batch 5000 --output grande.sql"
echo ""

echo "======================================================================"
echo "COMO CARREGAR OS DADOS GERADOS:"
echo "======================================================================"
echo ""

echo "OPÇÃO 1: Via Docker (Recomendado)"
echo "  # Copiar arquivo para container"
echo "  docker cp exemplo-10k.sql trino-small:/tmp/"
echo ""
echo "  # Executar no Trino"
echo "  docker compose exec trino-small trino \\"
echo "    --server http://localhost:8080 \\"
echo "    --user admin \\"
echo "    --file /tmp/exemplo-10k.sql"
echo ""

echo "OPÇÃO 2: Via CLI Externo"
echo "  trino \\"
echo "    --server http://localhost:8080 \\"
echo "    --user admin \\"
echo "    --catalog iceberg \\"
echo "    --schema analytics \\"
echo "    --file exemplo-10k.sql"
echo ""

echo "======================================================================"
echo "CENÁRIOS DE TESTE RECOMENDADOS:"
echo "======================================================================"
echo ""

echo "TESTE 1: Consultas Leves (cluster small)"
echo "  # Gerar dataset pequeno"
echo "  ./generate_data.py --records 50000 --days 7 --output teste-small.sql"
echo "  # Queries que filtram 1 dia → score < 0.3 → cluster small"
echo ""

echo "TESTE 2: Consultas Intermediárias (cluster medium)"
echo "  # Gerar dataset médio"
echo "  ./generate_data.py --records 500000 --days 90 --output teste-medium.sql"
echo "  # Queries com JOIN + filtro de 1 mês → 0.3 <= score <= 0.7 → medium"
echo ""

echo "TESTE 3: Consultas Pesadas (cluster large)"
echo "  # Gerar dataset grande"
echo "  ./generate_data.py --size-gb 5 --output teste-large.sql"
echo "  # Queries com subconsultas + sem filtros → score > 0.7 → large"
echo ""

echo "======================================================================"
echo "ESTIMATIVAS DE TAMANHO:"
echo "======================================================================"
echo ""
echo "  50.000 registros   = ~10 MB SQL    = ~100 MB Iceberg"
echo "  180.000 registros  = ~36 MB SQL    = ~400 MB Iceberg"
echo "  500.000 registros  = ~100 MB SQL   = ~1 GB Iceberg"
echo "  1.000.000 registros = ~200 MB SQL   = ~2 GB Iceberg"
echo "  5.000.000 registros = ~1 GB SQL     = ~10 GB Iceberg"
echo "  10.000.000 registros = ~2 GB SQL     = ~20 GB Iceberg"
echo ""

echo "======================================================================"
echo "DISTRIBUIÇÃO DOS DADOS GERADOS:"
echo "======================================================================"
echo ""
echo "  tenant_id: 50 tenants (T1 a T50) - distribuição uniforme"
echo "  status: ATIVO (90%) / INATIVO (10%)"
echo "  valor: Entre 10.0 e 1000.0 (distribuição uniforme)"
echo "  date: Distribuído uniformemente no range de dias"
echo "  document: JSON sintético com metadados"
echo "  surrogate_key: Único por registro (SK00000001, SK00000002, ...)"
echo ""

echo "======================================================================"
echo "VALIDAR DADOS CARREGADOS:"
echo "======================================================================"
echo ""
echo "  # Contar registros"
echo "  SELECT COUNT(*) FROM iceberg.analytics.dados;"
echo ""
echo "  # Verificar range de datas"
echo "  SELECT MIN(date), MAX(date) FROM iceberg.analytics.dados;"
echo ""
echo "  # Verificar distribuição de status"
echo "  SELECT status, COUNT(*) FROM iceberg.analytics.dados GROUP BY status;"
echo ""

echo "======================================================================"
echo "DICAS DE PERFORMANCE:"
echo "======================================================================"
echo ""
echo "  1. Use --batch maior para datasets grandes (ex: --batch 5000)"
echo "  2. Divida arquivos muito grandes para carregar em paralelo"
echo "  3. Ajuste memória do Trino se necessário (config.properties)"
echo ""

echo "======================================================================"
echo "DOCUMENTAÇÃO COMPLETA:"
echo "======================================================================"
echo ""
echo "  Leia: src/scripts/README_GENERATOR.md"
echo ""
echo "======================================================================"
